package main

import (
	"godatastructure/a012hashtable"
)

func main() {
	// a001arraylist.DoArrayList()
	// a002stackarray.DoStackArray()
	// a001arraylist.DoArrayListStack()
	// a001arraylist.DoArrayListIteratorStack()
	// a003recursion.DoRecursion()
	// a003recursion.DoFibonacci()
	// a003recursion.DoWalkFolder()
	// a004queue.DoQueue()
	// a004queue.DoCircleQueue()
	// a005link.DoLinkStack()
	// a005link.DoLinkQueue()
	// a006sortsearch.DoBubbleSort()
	// a006sortsearch.DoHeapSort()
	// a006sortsearch.DoQuickSort()
	// a006sortsearch.DoOddEvenSort()
	// a006sortsearch.DoMergeSort()
	// a006sortsearch.DoShellSort()
	// a006sortsearch.DoRadixSort()
	// a006sortsearch.DoCountSort()
	// a006sortsearch.DoTreeSelectSort()
	// a006sortsearch.DoCocktailSort()
	// a006sortsearch.DoMemSearch()
	// a006sortsearch.DoMapSearch()
	// a006sortsearch.DoBinSearch()
	// a006sortsearch.DoThirdSearch()
	// a007set.DoSet()
	// a008link.DoSingleLink()
	// a008link.DoSingleLinkFindMiddle()
	// a008link.DoDoubleLink()
	// a009threadsafe.DoThreadUnsafe()
	// a011heaptheadsafe.DoHeapSort()
	// a011heaptheadsafe.DoPriorityQueue()
	a012hashtable.DoHashTable()
	// graph.DemoAdd()
	// a102redblacktree.ReadBlackTreeMain()
	// a103bbplustree.BBplusTreeMain()
	// a104goset.GoSetMain()
	// a105radixtree.RadixTreeMain()
}
